name: tmdb
description: "A movies application using TMDB API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Networking
  dio: ^5.7.0
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

  # Local Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # State Management
  provider: ^6.1.2

  # UI Utils
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  
  # Navigation & Deep Linking
  go_router: ^14.2.1
  share_plus: ^7.2.2
  fluttertoast: ^8.2.4
  http: ^1.6.0
  connectivity_plus: ^7.0.0

dependency_overrides:
  code_builder: ^4.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.10.5
  retrofit_generator: 10.2.1
  drift_dev: ^2.14.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
